# Generated by Django 2.0.4 on 2018-04-25 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0003_animal'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExhibitNeighbors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(max_length=200)),
                ('fromExhibit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='zoo.Exhibit')),
                ('toExhibit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='neighbor_of', to='zoo.Exhibit')),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='zoo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='zoo.Zoo'),
        ),
    ]
