# Generated by Django 2.0.4 on 2018-04-30 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0004_auto_20180425_1442'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExhibitNeighbors',
            new_name='ExhibitNeighbor',
        ),
    ]
