# Generated by Django 2.0.4 on 2018-04-30 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0005_auto_20180430_0352'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoo',
            name='logoFileName',
            field=models.CharField(help_text='Enter Logo File Name', max_length=200, null=True),
        ),
    ]
