# Generated by Django 2.0.4 on 2018-05-01 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0007_auto_20180501_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibitneighbor',
            name='direction',
            field=models.CharField(blank=True, choices=[('n', 'North'), ('s', 'South'), ('e', 'East'), ('w', 'West'), ('nw', 'North West'), ('ne', 'North East'), ('sw', 'South West'), ('se', 'South East')], help_text='Enter Direction', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='exhibitneighbor',
            name='fromExhibit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fromExhibit', to='zoo.Exhibit'),
        ),
        migrations.AlterField(
            model_name='exhibitneighbor',
            name='toExhibit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='toExhibit', to='zoo.Exhibit'),
        ),
    ]
