# Generated by Django 2.0.4 on 2018-05-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0008_auto_20180501_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='behaviorDescription',
            field=models.TextField(help_text='Enter a description of the Behavior of the animal', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='dietDescription',
            field=models.TextField(help_text='Enter a description of the Diet of the animal', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='habitatDescription',
            field=models.TextField(help_text='Enter a description of the Habitat of the animal', max_length=1000, null=True),
        ),
    ]
