# Generated by Django 2.0.4 on 2018-05-03 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0009_auto_20180502_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='soundFileName',
            field=models.CharField(blank=True, help_text='Enter sound file name', max_length=200, null=True),
        ),
    ]
