# Generated by Django 2.0.4 on 2018-05-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0010_auto_20180503_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='imageFileName',
            field=models.CharField(help_text='Enter logo file name (images/)', max_length=200, null=True),
        ),
    ]
