# Generated by Django 2.0.4 on 2018-05-06 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0011_auto_20180503_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='imageFileName',
            field=models.CharField(help_text='Enter image file name (images/)', max_length=200, null=True),
        ),
    ]
