# Generated by Django 2.0.4 on 2018-05-07 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0012_auto_20180506_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='soundFileName',
        ),
        migrations.AddField(
            model_name='animal',
            name='livingPeriod',
            field=models.CharField(blank=True, help_text='Enter the period of time they lived', max_length=200, null=True),
        ),
    ]
