# Generated by Django 2.0.4 on 2018-05-07 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0013_auto_20180507_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='behaviorDescription',
            field=models.TextField(blank=True, help_text='Enter a description of the Behavior of the animal', max_length=1000, null=True),
        ),
    ]
